### ISSUE TITLE
unknown encoding:future_fstrings

### ISSUE THREAD

**Issue by JuHey** [flying-sheep/anndata2ri#14]
I am having an issue with installing the anndata2ri package. I am getting the following error message when trying to import anndata2ri from jupyter lab:
`  File "<string>", line unknown
SyntaxError: unknown encoding for '/usr/local/lib/python3.7/site-packages/get_version.py': future_fstrings`

Here is the install info:
`git clone https://github.com/flying-sheep/anndata2ri.git`
`cd anndata2ri`
`pip3 install .`

Install output: 
`Installing collected packages: future-fstrings, get-version, anndata2ri
Successfully installed anndata2ri-0.1.dev62-58b507d future-fstrings-1.0.0 get-version-2.0.6`

MacOS10.13.6; Python3.7

Any suggestions kindly appreciated.

**Comment by JuHey** [comment]
Resolved itself after restarting jupyter lab!

**Comment by flying-sheep** [comment]
Yup, after installing the future-fstrings package and restarting the interpreter, everything should work :smile:
