### ISSUE TITLE
not following the conversion step

### ISSUE THREAD

**Issue by MichaelPeibo** [flying-sheep/anndata2ri#15]
Hi @flying-sheep 
I am using anndata2ri to convert sce object to anndata.
When I tried python step in the main page, I got:

> AttributeError: module 'anndata2ri' has no attribute 'activate'

any suggestion?
Thanks!

**Comment by flying-sheep** [comment]
You don’t have all dependencies installed.

Currently the module only shows an ImportWarning in that case, which I hope to change in the future.

I think you can see that warning by doing `python3 -Wd anndata2ri.py`

**Comment by MichaelPeibo** [comment]
Hi @flying-sheep 
Thanks for response, 
I move test.ipynb file into the subdirectory of anndata2ri directory, now the code below no longer report the error.
```
import anndata2ri
from rpy2.robjects import r
anndata2ri.activate()
```
However, when I tried to use the code below to do conversion, I got this error:
`adata = r('as('/home/xupb/anndata2ri/my_sce.RDS',"SingleCellExperiment")')`

>   File "<ipython-input-15-97d3c18afb3a>", line 1
>     adata = r('as('/home/xupb/anndata2ri/my_sce.RDS',"SingleCellExperiment")')
>                                                                                                                             ^
> SyntaxError: invalid syntax

**Comment by flying-sheep** [comment]
yes:

```py
 adata = r('as('/home/xupb/anndata2ri/my_sce.RDS',"SingleCellExperiment")')
```

should be

```py
 adata = r('as("/home/xupb/anndata2ri/my_sce.RDS","SingleCellExperiment")')
```

**Comment by smk5g5** [comment]
Hi I also tried your solution but I keep getting 

```
>>> adata = r('as("gbm_sce.rds","SingleCellExperiment")')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/rpy2/robjects/__init__.py", line 438, in __call__
    res = self.eval(p)
  File "/usr/local/lib/python3.9/dist-packages/rpy2/robjects/functions.py", line 198, in __call__
    return (super(SignatureTranslatedFunction, self)
  File "/usr/local/lib/python3.9/dist-packages/rpy2/robjects/functions.py", line 125, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/rpy2/rinterface.py", line 677, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in as("gbm_sce.rds", "SingleCellExperiment") :
  no method or default for coercing “character” to “SingleCellExperiment”
```
